create table filters (
    id int8 not null generated by default as identity,
    user_id int8 null,

    filter json not null,
    filter_url varchar not null,

    constraint filters_pkey primary key (id),
    constraint filters_user_id foreign key (user_id) references users (id) deferrable initially deferred
);
